### ISSUE TITLE
Help running code

### ISSUE THREAD

**Issue by ahsteven** [MG2033/A2C#3]
I am not sure what i am doing wrong but I am in the A2C folder and when I run:

(gym) teves@teves:~/A2C$ python main.py config/breakout.json
usage: main.py [-h] [--version] [--config CONFIG]
main.py: error: unrecognized arguments: config/breakout.json
Add a config file using '--config file_name.json'

or if I run:

(gym) teves@teves:~/A2C$ python main.py --config config/breakout.json
Add a config file using '--config file_name.json'

How shall I run this?

**Comment by MG2033** [comment]
There was an issue regarding the bunch library. It's fixed now. You should be able to run.

Tell me if you face any more issues.

**Comment by ahsteven** [comment]
Yes it works now running the command:
python main.py --config config/pong.json
Thank you

**Comment by ahsteven** [comment]
Hi Mostafa,

I am trying to understand A2C in detail and I have read through your code as well as the openai baselines code. I have a couple of questions.

Why do we need a train model? Could we not just update the step model after the rollout? Or does the train model serve as some sort of placehoder? Also, why are the parameters in the train model set to be reused and the step model not. I am also a little confused on how the step model parameters get updated.

I appreciate any help you can give me on this.

**Comment by MG2033** [comment]
Ok. I will do it in the next few days.
